name: Build and Deploy

on:
  push:
    branches:
      - master   # 👈 Cada vez que hagas push a main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Compilar proyecto
      - name: Build Next.js
        run: npm run build

      # 5. Subir build a la rama "build"
      - name: Deploy to build branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: build        # 👈 rama destino
          folder: out          # 👈 carpeta generada (usa .next si no exportas)
